name: Build vprofile project
on: workflow_dispatch
jobs:
  builder:
    runs_on: ubuntu-latest
    steps:
      - name: Message
        run: echo "This job will install jdk, maven & build the project"
      - name: Install dependencies
        run: |
              sudo apt update
              sudo apt install openjdk-11-jdk -y
              sudo apt install maven -y
              
        
